# Specify a non-default branch for pull requests for pip

version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    # Raise pull requests for version updates
    # to pip against the `develop` branch
    target-branch: "development"
    # Labels on pull requests for version updates only
    labels:
      - "npm dependencies"
