<!-- vin array object $SEND_TXVIN_ARRAYNUM start -->
                  <tr>
                    <th rowspan="4">$SEND_TXVIN_ARRAYNUM</th>
                    <th>$SEND_LABEL_TXID</th>
                    <td class="text-break text-wrap"><a href="$URL/method/txidinfo?txid=$SEND_TXVIN_TXID&vout=$SEND_TXVIN_VOUT&nexturl=txidinfo">$SEND_TXVIN_TXID</a></td>
                  </tr>
                  <tr>
                    <th>$SEND_VOUT</th>
                    <td>$SEND_TXVIN_VOUT</td>
                  </tr>
                  <tr>
                    <th>$SEND_SCRIPTSIG</th>
                    <td class="text-break text-wrap">$SEND_TXVIN_SCRIPTSIG</td>
                  </tr>
                  <tr>
                    <th>$SEND_SEQUENCEID</th>
                    <td>$SEND_TXVIN_SEQID</td>
                  </tr>
                  <!-- vin array object $SEND_TXVIN_ARRAYNUM end -->