name: Build, Test and Package PRs to Main Branch

on:
  pull_request:
    branches: [main]

jobs:
  'main--build-test-package-publish':
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Install Node
        uses: actions/setup-node@v2
        with:
          node-version: 15
          cache: yarn

      - name: Install packages with Yarn
        run: yarn install --frozen-lockfile

      - name: Build with webpack
        run: yarn build

      - name: Run tests
        run: yarn checks

      - name: Package and publish with electron-builder
        run: yarn package:publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
